### ISSUE TITLE
Problem with font color on iOS

### ISSUE THREAD

**Issue by M1chlCZ** [nextchapterstudio/walletconnect_qrcode_modal_dart#11]
Having an issue when font is unreadable on iOS, I tried to wrapping it into Theme widget, but it didn't helped. Is there any way how to change the font to black?

Here is the image showing this problem:
![image](https://user-images.githubusercontent.com/66187879/195136058-8422c9ef-cd26-4b66-9c91-150f3f520654.png)

Flutter version:  3.3.4 stable channel

**Comment by 3ph** [comment]
Hi Michal, I can see why this would happen. I'll make some changes to make the styling more flexible.

**Comment by M1chlCZ** [comment]
Thank you very much.

**Comment by 3ph** [comment]
Hi Michal, I've pushed a new version with a quick fix, planning to make the modal more customizable in the next version.

**Comment by M1chlCZ** [comment]
Thank for your fast response and keep up the good work! : )
