### ISSUE TITLE
using WalletConnect callback

### ISSUE THREAD

**Issue by pango0608** [nextchapterstudio/walletconnect_qrcode_modal_dart#18]
I am gonna build a flutter app with qrcode modal for wallet integration.
But I want my app remember my wallet session. And for this, i want to using walletconnect callback in modalbuilder. 
But I am not sure how to use walletconnect callback.
Please share some sample code to show how to detect which wallet users select from wallet list on iOS.
This is so urgent problem. I searched google whole day but i can't find answer.
Thanks.

**Comment by 3ph** [comment]
You mean something like described here https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart/issues/6?

**Comment by pango0608** [comment]
Yes. I've already solved it.
But it was very difficult to customize current qr modal.
For example, I want to change number of walllets on the QR Code modal wallet list. 
For this, i need to add bunch of lines of code.
Is there any other way more simple and efficient ?
![Screenshot_1](https://user-images.githubusercontent.com/118023903/206860000-5eb5d79e-996d-4d7e-b277-04ef34266d19.png)

**Comment by 3ph** [comment]
That's right, normally you only need to customize the UI, not the data. I could extend the `copyWith` to cover also the data parameters.

**Comment by pango0608** [comment]
yeah. that's what i am gonna do. i saw many developers wanna customize call back or any other data related to wallet modal on stackoverflow.
honestly, for above code, i've analyze whole  library 2 days,.
please add those options with` copyWith`

**Comment by 3ph** [comment]
@pango0608 New version released.

**Comment by pango0608** [comment]
thanks @3ph
i would like to take part in your project

**Comment by 3ph** [comment]
Hey @pango0608 - no problem. Do you have any improvements/fixes in mind? You can always open a PR.

**Comment by 3ph** [comment]
Closing for now, you can create a new issue or PR with an improvement.
