### ISSUE TITLE
Error after cancel the connection in the wallet

### ISSUE THREAD

**Issue by juanArismendy** [nextchapterstudio/walletconnect_qrcode_modal_dart#20]
This issue is happening after cancel the connection inside the wallet app, which is breaking the flow.
thanks for any help or fix to handle this error

![Screenshot 2023-01-26 at 3 53 55 PM](https://user-images.githubusercontent.com/86382963/214948287-31ed7946-e1dc-4bde-bed3-bb583e9c73e2.png)
![Screenshot 2023-01-26 at 3 54 24 PM](https://user-images.githubusercontent.com/86382963/214948389-3c560a30-bf34-4f18-bfef-cccec125753f.png)

**Comment by 3ph** [comment]
I've fixed the bug and released a new version 0.1.2.
