### ISSUE TITLE
Cannot connect to Trust Wallet.

### ISSUE THREAD

**Issue by canismayorisxl** [nextchapterstudio/walletconnect_qrcode_modal_dart#23]
Hello, I was playing around with this package and realized that the package somehow does not allow for a connection with TrustWallet. (Metamask works just fine). Any ideas on why that is and how it can be fixed?.

**To reproduce**
Run the example app, and try to connect to TrustWallet (Through openUrl OR QRScanner).

**Comment by canismayorisxl** [comment]
Small update, TrustWallet seems to only accept rpc URLs of main net. Everything worked fine after trying to connect with TrustWallet using a main net URL. So I will close this issue.

**Comment by karenpoveda29** [comment]
@ZamirAmiri I'm having the same issue with Trust Wallet. Could you please expand on your solution? I see that there's already reference to a rcp url in the file `ethereum_test_connector` but I don't understand what you mean by "trying to connect with TrustWallet using a main net URL"

![image](https://user-images.githubusercontent.com/53981435/224151426-39d84167-fec3-46f7-813d-200b65738b91.png)

**Comment by Angelsnevercry** [comment]
@karenpoveda29 We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/

**Comment by canismayorisxl** [comment]
@karenpoveda29
Here is my implementation.

![Screenshot from 2023-03-10 12-42-38](https://user-images.githubusercontent.com/21984555/224307417-08f76f1d-bc3f-421d-b6ea-1a428ac7eabc.png)
![Screenshot from 2023-03-10 12-42-58](https://user-images.githubusercontent.com/21984555/224307497-34087436-0662-41f9-b161-f7426ce233ac.png)
![Screenshot from 2023-03-10 12-43-23](https://user-images.githubusercontent.com/21984555/224307586-7187fa74-f027-42cc-ac7d-4a2beda48663.png)

Hope this helps.

**Comment by karenpoveda29** [comment]
@ZamirAmiri I have basically the same thing as you. But still not working. It navigates all the way to the wallet but it doesn't show the message to connect or reject. That's the problem I'm having.

**Comment by emma-r-slight** [comment]
@karenpoveda29 With Trust wallet you have to manually switch to the correct chain 😢 (this is done in the Trust wallet app when you connect).  It doesn't detect which chain you want to connect to and prompt you to change as other wallets do.

**Comment by bansalgaurav852** [comment]
anyone got any fix??

**Comment by 3ph** [comment]
@bansalgaurav852 You have to address this with TrustWallet team unfortunately.

**Comment by bansalgaurav852** [comment]
> @bansalgaurav852 You have to address this with TrustWallet team unfortunately.

but walletconnect web library working fine with trust wallet connection so i don't think issue in trust wallet

**Comment by 3ph** [comment]
As discussed in the other thread, it seems that you are using V2 web library. This package only supports V1.
