### ISSUE TITLE
WalletConnectQrCodeModal singMessage returns void

### ISSUE THREAD

**Issue by canismayorisxl** [nextchapterstudio/walletconnect_qrcode_modal_dart#24]
I've been going through the code and saw that .signMesssage returns a void, while the connector within the class returns Future<dynamic>.

Suggestion 
WalletConnectQrCodeModal should return dynamic as well.

**Code change:**
`  Future<void> sendCustomRequest({
    required String method,
    required List<dynamic> params,
    String? topic,
  })`

**to:**
`Future<dynamic> sendCustomRequest({
    required String method,
    required List<dynamic> params,
    String? topic,
  })`

This way you won't be forced to call the underlying function to get a response back.

**Comment by 3ph** [comment]
Thanks for the suggestions. Updated in version 0.3.1
