### ISSUE TITLE
Switch network

### ISSUE THREAD

**Issue by bansalgaurav852** [nextchapterstudio/walletconnect_qrcode_modal_dart#25]
hello i want to show switch network popup in metamask if user not connect to binance chain how can i do that??

**Comment by 3ph** [comment]
Hi, this is not possible with WalletConnect. When you send a session request, you can specify the chain ID but it's up to the Wallet app how it handles the request if the current network is different than the requested chain ID.

**Comment by bansalgaurav852** [comment]
but the same functionality is in web or in react

**Comment by 3ph** [comment]
Functionality of switching network from the dApp in the Wallet?

**Comment by bansalgaurav852** [comment]
in web when i call switch network function it opens a popup in my wallet and ask me to  *switch network* when i accept it network change

**Comment by 3ph** [comment]
Are we talking about V1 here? There is no such official command in V1. Which web app/library are you using?

**Comment by bansalgaurav852** [comment]
> Are we talking about V1 here? There is no such official command in V1. Which web app/library are you using?

in web it's v2 as i had to add project id .

**Comment by 3ph** [comment]
This package is wrapper around https://pub.dev/packages/walletconnect_dart which only supports V1. For V2 I suggest you use the official https://pub.dev/packages/walletconnect_flutter_v2 package.
