### ISSUE TITLE
FormatException when signing transaction after connecting using "Connect" button

### ISSUE THREAD

**Issue by jasonhtpham** [nextchapterstudio/walletconnect_qrcode_modal_dart#27]
I used the default `walletButtonBuilder` for Android which shows me a "Connect" button to connect my account on Pera Wallet. Then, I faced this error

```
Error: FormatException: Invalid character (at character 77)
I/flutter (10855): gqNzaWfEQIwtNFWFUDYnI49KtgVk5nGLCiEP9M/F7p4Zz2acj2FNEdZT3Dq56o+hKaSTYTzrU229
```

### When I tried to sign the transaction in this function:
```
@override
  Future<String?> optInApp({
    required int appId,
  }) async {
    logger.i("Opting in to app: $appId");

    if (await optedIn(appId)) {
      logger.i("Already opted in to app: $appId");
      return null;
    }

    final sender =
        Address.fromAlgorandAddress(_connector.connector.session.accounts[0]);

    // Fetch the suggested transaction params
    final params = await _algorand.getSuggestedTransactionParams();

    // Build the transaction
    final transaction = await (ApplicationOptInTransactionBuilder()
          ..sender = sender
          ..noteText = 'Opt in to app $appId from $sender'
          ..applicationId = appId
          ..suggestedParams = params)
        .build();

    logger.i("Tx created: $transaction");

    try {
      // Sign the transaction
      final txBytes = Encoder.encodeMessagePack(transaction.toMessagePack());
      logger.i("Tx bytes: $txBytes");

      final signedBytes = await _provider.signTransaction(
        txBytes,
        params: {
          'message': 'Opt in to app $appId from $sender',
        },
      );

      logger.i("Tx signed: $signedBytes");

      // Broadcast the transaction
      final txId = await _algorand.sendRawTransactions(
        signedBytes,
        waitForConfirmation: true,
      );
      return txId;
    } catch (e) {
      final err = _tryCast(e, fallback: AlgorandException);
      if (err is AlgorandException) {
        AlgorandException error = err as AlgorandException;
        debugPrint('Error: ${error.message}');
      } else {
        debugPrint('Error: $e');
      }
      return null;
    }
  }
```

### I tried to debug it and found that it happened when I tried to sign the transaction
```
      final txBytes = Encoder.encodeMessagePack(transaction.toMessagePack());
      final signedBytes = await _provider.signTransaction(
        txBytes,
        params: {
          'message': 'Opt in to app $appId from $sender',
        },
      );
```

### My initialization code and the `connect` method in my `AlgorandConnector` class:
```
AlgorandConnector() {
    _connector = WalletConnectQrCodeModal(
      connector: WalletConnect(
        bridge: 'https://bridge.walletconnect.org',
        clientMeta: const PeerMeta(
          // <-- Meta data of your app appearing in the wallet when connecting
          name: 'Shark Tank DApp',
          description: 'Shark Tank DApp',
          url: 'https://walletconnect.org',
          icons: [
            'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
          ],
        ),
      ),
    );

    _provider = AlgorandWalletConnectProvider(_connector.connector);
  }

  T? _tryCast<T>(dynamic value, {T? fallback}) {
    try {
      return (value as T);
    } on TypeError catch (_) {
      return fallback;
    }
  }

  @override
  Future<SessionStatus?> connect(BuildContext context) async {
    return await _connector.connect(context, chainId: 4160);
  }
```

It used to work perfectly fine when I tested it a few days ago. I only faced this error today. It also happened when I tested on a different device. Besides, if I connect to the Dapp using the QR Code, everything works perfectly fine. But I am working on a mobile application so I need the Deep Linking method to work.

This is the screenshot of the error
![image](https://user-images.githubusercontent.com/61170796/228142114-c7d596a1-5813-4fa9-ada0-16afed1a0e26.png)

**Comment by 3ph** [comment]
Hi. I'm a bit confused - does this happen when you connect or when you try to sign the transaction? Can you see where exactly does the exception occur?

**Comment by jasonhtpham** [comment]
It occurs when I sign the transaction. I had a few loggers set, I could get the loggers printed until the txBytes, signedBytes was not printed.

**Comment by 3ph** [comment]
I see, so an issue with communicating with Algorand network. From your code it seems that you are using https://github.com/RootSoft/algorand-dart package? Have you tried following the flow in the example?

```dart
// Fetch the suggested transaction params
final params = await algorand.getSuggestedTransactionParams();

// Build the transaction
final transaction = await (PaymentTransactionBuilder()
    ..sender = account.address
    ..note = 'Hi from Flutter'
    ..amount = Algo.toMicroAlgos(5)
    ..receiver = recipient
    ..suggestedParams = params)
  .build();

// Sign the transaction
final signedTx = await transaction.sign(account);

// Send the transaction
final txId = await algorand.sendTransaction(signedTx);
```

**Comment by jasonhtpham** [comment]
That flow requires an `account`, which I am not able to retrieve except asking for user's mnemonic, but I am wanting to make use of the wallet instead of managing my user's account

**Comment by jasonhtpham** [comment]
It used to work perfectly fine a few days ago. Are there any updates from WalletConnect that might be the cause?

**Comment by 3ph** [comment]
That code you are using was originally created by @RootSoft (https://github.com/RootSoft) for the `walletconnect_dart` package. He is also a creator of the `algorand_dart` package used here. The `walletconnect_dart` package hasn't been updated in a long time but there might have been some change in the Algorand network causing this.

Only thing which could have changed from WalletConnect side (or rather the accompanying app) is the `account.address`. I guess you can confirm that it is still the same as previously.

Other than that since the code is the same (unless you updated the `algorand_dart` package) there must have been some change in the Algorand node it's using. I would suggest talking to @RootSoft, he would be the best person to help here.

**Comment by 3ph** [comment]
Issue with Algorand network/package
