### ISSUE TITLE
Function WalletConnect returns undefined

### ISSUE THREAD

**Issue by ZeroTimeDrift** [nextchapterstudio/walletconnect_qrcode_modal_dart#29]
Hey there, trying to test out the library using the example code provided, seems as though I'm getting issues with two things here, WalletConnect and PeerMeta are undefined, even after installing wallet connect dart. I managed to resolve the PeerMeta issue by changing it to WCPeerMeta, but can't find the equivalent for the connector

`  final qrCodeModal = WalletConnectQrCodeModal(
    
    connector: WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: PeerMeta(
        // <-- Meta data of your app appearing in the wallet when connecting
        name: 'QRCodeModalExampleApp',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    ),
  );
}`

**Comment by 3ph** [comment]
Hi, the package is using `walletconnect_dart` package to communicate with WalletConnect - connector is required otherwise communication wouldn't be possible.

You can have a look [here](https://pub.dev/packages/walletconnect_dart) for more information about the `connector`.

**Comment by ZeroTimeDrift** [comment]
Got it, thanks for your help, I managed to resolve the issue but now I can't seem to get the walletconnect modal to pop up, here is my code: 
`Future<void> ethereumProvider() async {
// Create a connector
  final qrCodeModal = WalletConnectQrCodeModal(
    connector: WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: const PeerMeta(
        // <-- Meta data of your app appearing in the wallet when connecting
        name: 'QRCodeModalExampleApp',
        description: 'WalletConnect Developer App',
        url: 'localhost:3000',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    ),
  );
}`

When I call ethereumProvider, nothing happens
`ElevatedButton(
              onPressed: () async {
                await ethereumProvider();
              },
              child: Text('Connect wallet'),
            ),`

**Comment by 3ph** [comment]
Yes, creating the `WalletConnectQrCodeModal` doesn't show anything yet - you have to call `connect`. I realized this is not mentioned in the README so I'll add it there.
