### ISSUE TITLE
TokenPocket cannot be opened

### ISSUE THREAD

**Issue by peyton-v5** [nextchapterstudio/walletconnect_qrcode_modal_dart#31]
[default] Failed to open URL tpoutside://: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=225, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}

**Comment by LiRenGuo** [comment]
I have this problem too, did you solve it?

**Comment by peyton-v5** [comment]
> 我也遇到这个问题，请问你解决了吗？
Not yet resolved
