### ISSUE TITLE
TokenPocket can't connect

### ISSUE THREAD

**Issue by peyton-v5** [nextchapterstudio/walletconnect_qrcode_modal_dart#32]
can you give me a little help

**Comment by 3ph** [comment]
Sorry, I'd need a bit of context to help

**Comment by peyton-v5** [comment]
TokenPocket in https://registry.walletconnect.org/data/wallets.json, native in mobile is tpoutside. tpoutside can't open tp wallet, after testing, it can be opened by changing it to tpdapp, but the connection is unsuccessful

**Comment by 3ph** [comment]
Neither `tpoutside` nor `tpdapp` can be opened with TokenPocket app installed. I suggest you raise a ticket with TokenPocket team to fix the registry entry. The package basically passes WC link to the Wallet app so if you can't see the connection dialog in the Wallet app that would indicate that the Wallet app doesn't handle WC links properly.

Feel free to reopen the ticket if you still have issues after TokenPocket fixes.
