### ISSUE TITLE
How to connect with Coinbase Wallet? 

### ISSUE THREAD

**Issue by LiRenGuo** [nextchapterstudio/walletconnect_qrcode_modal_dart#33]
I tried using this package to connect to Coinbase Wallet but it didn't work. Can this package connect to Coinbase Wallet?. Thanks.

**Comment by 3ph** [comment]
Hi, Coinbase Wallet app doesn't support WalletConnect protocol, you have to use Coinbase SDK to connect.

Please see [here](https://forums.coinbasecloud.dev/t/walletconnect-v2-0-support/1746/4)
