### ISSUE TITLE
How to deeplink back to wallet app after connection.

### ISSUE THREAD

**Issue by ZeroTimeDrift** [nextchapterstudio/walletconnect_qrcode_modal_dart#34]
Hey there, after connecting the modal, if I try to do a personalSign action, it doesn't redirect me back to the metamask app, I have to manually go back, is this expected behaviour? The signature shows on metamask and deeplinks back to app but no initial deeplink into metamask.

**Comment by 3ph** [comment]
Hi @ZeroTimeDrift - you can use `connector.openWalletApp()` when you want to navigate back to the Wallet app. Have a look at the example app, it's being used when the testing amount is sent.

**Comment by ZeroTimeDrift** [comment]
Gotcha, thanks for that, it works great but run into issues when doing a sign transaction after awaiting the walletconnect connection as the user is not fully loaded back into the app once this is being called. It works if I delay the function by a few seconds.

For context, here is my code:
```
await initializeProvider(
          context,
          "https://bridge.walletconnect.org",
          'MoonGate',
          'An example app showcasing Sign in With Ethereum',
          'localhost:3000',
          'https://www.joinef.com/wp-content/uploads/2023/03/MoonGate-5-Praneet-Sinha-700x700.png',
        );
        await signInWithEthereum(
            'localhost:3000', 'I love pizza', 'localhost:3000', '1', '1');
```
            
Where `signInWithEthereum()` calls `openWalletApp()`, are there any callbacks that I can use to ensure that `signInWithEthereum()` is only called once the user is fully re-directed back in the app? The event listeners for the session get updated immediately and I can't use those.

**Comment by 3ph** [comment]
You can detect if the app is back in the foreground using `WidgetsBindingObserver` with `didChangeAppLifecycleState` method. Would that work for you?

**Comment by ZeroTimeDrift** [comment]
Worked like a charm, cheers @3ph!
