### ISSUE TITLE
Walletconnect v2

### ISSUE THREAD

**Issue by artemvolkovvv** [nextchapterstudio/walletconnect_qrcode_modal_dart#36]
Hello! Is there any plans to update this beautiful package to wc2?

**Comment by 3ph** [comment]
Hi, there is an official Flutter/Dart support now from WalletConnect - the modal package can be found here https://github.com/WalletConnect/Web3ModalFlutter.

**Comment by artemvolkovvv** [comment]
Yeap, have seen it. But it's not fits perfectly to our app due to some reasons, and it will take a lot of time to reintegrate as it uses walletconnect_flutter(
Anyway, thank you!
