### ISSUE TITLE
the connection failed

### ISSUE THREAD

**Issue by liangliang521** [nextchapterstudio/walletconnect_qrcode_modal_dart#37]
The wallet did not link successfully after jumping to the app，and will not return to the app。

**Comment by 3ph** [comment]
Hi, I can't really help you without more information. I suggest you try the example app with the WalletConnect testing wallet and see if it works.

**Comment by 3ph** [comment]
The issue is likely caused by the bridge servers taken offline with V1 sunset. If not, please reopen and provide more information.
