### ISSUE TITLE
I face this error when I try to connect metamask wallet and I try to run example but same problem in example app [Ios & android]

### ISSUE THREAD

**Issue by Ashishkakadiya243** [nextchapterstudio/walletconnect_qrcode_modal_dart#39]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed host lookup: 'p.bridge.walletconnect.org' (OS Error: No address associated with hostname, errno = 7)
E/flutter (16632): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:719:35)
E/flutter (16632): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1912:26)
E/flutter (16632): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (16632): #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297:22)
E/flutter (16632): #4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
E/flutter (16632): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2482:26)
E/flutter (16632): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2924:12)
E/flutter (16632): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2929:12)
E/flutter (16632): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2784:12)
E/flutter (16632): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2622:7)
E/flutter (16632): #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
E/flutter (16632): #11     WebSocket.connect (dart:_http/websocket.dart:320:22)
E/flutter (16632): #12     new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:81:28)
E/flutter (16632): #13     connect (package:web_socket_channel/src/_connect_io.dart:15:24)
E/flutter (16632): #14     new WebSocketChannel.connect (package:web_socket_channel/src/channel.dart:115:16)
E/flutter (16632): #15     ReconnectingWebSocket.open (package:walletconnect_dart/src/network/reconnecting_web_socket.dart:86:33)
E/flutter (16632): #16     ReconnectingWebSocket._onClose.<anonymous closure> (package:walletconnect_dart/src/network/reconnecting_web_socket.dart:157:7)
E/flutter (16632): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (16632): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (16632): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (16632): #20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (16632): #21     _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (16632): #22     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:242:18)
E/flutter (16632): <asynchronous suspension>
E/flutter (16632): #23     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:241:17)
E/flutter (16632): <asynchronous suspension>

**Comment by 3ph** [comment]
Hi, WalletConnect v1.0 has been sunset and the bridge servers taken offline. Please see more information [here](https://medium.com/walletconnect/walletconnect-v1-0-shutdown-what-to-expect-and-how-to-prepare-2ae443d6d7bd)

All WC users need to migrate to WalletConnect v2.0
