### ISSUE TITLE
DarkTheme and Close Modal

### ISSUE THREAD

**Issue by papalardo** [nextchapterstudio/walletconnect_qrcode_modal_dart#4]
First of all, I'd like to congratulate you for the great job you've done on this plugin. 
It worked fine for me on windows and android. 
I just missed the dark theme or override theme:

![image](https://user-images.githubusercontent.com/17734894/181847050-f677f70c-fb57-4c17-b6b8-87f5bef2ec29.png)

And I wasn't able to close the modal, just with the user interaction on the screen.

Could you help me with this?

**Comment by 3ph** [comment]
Thanks for raising the issues!

The view is implemented as a dialog so you can close it by tapping outside the dialog. I could add a close button to make it explicit.

Do you have link to how is the modal supposed to look like in the dark mode?

**Comment by 3ph** [comment]
Closing as stale.
