### ISSUE TITLE
How to save state after connecting?

### ISSUE THREAD

**Issue by peyton-v5** [nextchapterstudio/walletconnect_qrcode_modal_dart#6]
After connecting, if you reopen the App, you need to scan the code or jump to the wallet to re-walletconnect to connect. How to ensure that the next time you open the app, you can find the previously connected walletconnect

**Comment by 3ph** [comment]
The package is only UI wrapper around `walletconnect_dart` library. By default the connector is created for you but you can also create your own and pass it in.

In the constructor you can pass your own `sessionStorage`:

```dart

final connector = WalletConnect(
   url: url,
   sessionStorage: sessionStorage,
   ....
);
``` 
The library then handles saving and removing the session for you.

**Comment by peyton-v5** [comment]
sorry i didn't find much information about sessionStorage, can you tell me how it is used

**Comment by peyton-v5** [comment]
> The package is only UI wrapper around `walletconnect_dart` library. By default the connector is created for you but you can also create your own and pass it in.
> 
> In the constructor you can pass your own `sessionStorage`:
> 
> ```dart
> final connector = WalletConnect(
>    url: url,
>    sessionStorage: sessionStorage,
>    ....
> );
> ```
> 
> The library then handles saving and removing the session for you.

sorry i didn't find much information about sessionStorage, can you tell me how it is used

**Comment by 3ph** [comment]
You can find documentation [here](https://pub.dev/documentation/walletconnect_dart/latest/walletconnect/SessionStorage-class.html). It's an abstract class, you have to implement couple of methods. 

It's up to you how you implement the storage but `WalletConnectSession` has `toJson()` and `fromJson()` methods so you can store the session as `String` (for example using `shared_preferences`).

**Comment by 3ph** [comment]
Closing as stale.
